dataset :
  root : "data/Poleno/"                                 # root folder of the dataset
  img_channels : 1                                      # grayscale images
  img_size : 200                                        # original image size
  img_interpolation : 224                               # size after interpolation or "Null"
  labels_train : labels_train.csv                       # training labels
  labels_val : labels_val.csv                           # validation labels
  labels_test : labels_test.csv                         # test labels
  filenames : filenames                                 # column name containing filenames
  img_path : filenames                                  # column name containing relative image path from root

training :
  lr : 0.0001
  batch_size : 8
  num_epochs : 5
  validation_step : 100

